# Generated by Django 5.0.3 on 2024-03-21 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 3, 21, 18, 30, 27, 238970))),
                ('data', models.TextField()),
                ('previous_hash', models.CharField(max_length=250)),
                ('hash', models.CharField(max_length=250)),
            ],
        ),
    ]
